# Generated by Django 4.1.3 on 2023-03-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='Activities',
            new_name='activities',
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone',
            field=models.BigIntegerField(unique=True),
        ),
    ]
