# Generated by Django 4.1.3 on 2023-03-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0002_rename_activities_perevaladded_activities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladdedspractivitiestypes',
            old_name='PerevalAdded',
            new_name='perevalAdded',
        ),
        migrations.RenameField(
            model_name='perevaladdedspractivitiestypes',
            old_name='SprActivitiesTypes',
            new_name='sprActivitiesTypes',
        ),
    ]
