# Generated by Django 4.1.3 on 2023-04-01 08:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MountainCoord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=200)),
                ('longitude', models.FloatField(max_length=200)),
                ('height', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Turist',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(blank=True, max_length=255, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10)),
                ('connect', models.TextField(null=True)),
                ('winter', models.CharField(blank=True, max_length=50, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=50, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=50, null=True, verbose_name='Весна')),
                ('coords', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='mountain.mountaincoord')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain.images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_mount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
