# Generated by Django 4.1.3 on 2023-04-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_mount', to='mountain.turist'),
        ),
    ]
